services:
  trino:
    image: 'trinodb/trino:latest'
    hostname: trino
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  postgresdb:
    image: 'postgres:latest'
    hostname: postgresdb
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    networks:
      - trino-network
  
  hive-metastore:
    #build: ./hive-metastore
    hostname: hive-metastore
    image: 'docker.dev.digitaleconomy.gov.kh/trino-minio-pg-docker-hive-metastore:v1.0.0'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_TYPE: postgres
      METASTORE_DB_HOSTNAME: postgresdb
      METASTORE_DB_PORT: 5432
    depends_on:
      - postgresdb
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - trino-network
  
  redis:
    image: redis:latest
    container_name: superset_redis
    ports:
      - "6379:6379"
    networks:
      - trino-network

  superset:
    image: apache/superset:latest
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_WEBSERVER_TIMEOUT: 60
      SUPERSET_SECRET_KEY: 'your_super_secret_key'
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: superset_db
      POSTGRES_HOST: postgresdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgresdb
      - redis
    networks:
      - trino-network
    volumes:
      - ./supserset/superset_config.py:/app/pythonpath/superset_config.py 

volumes:
  minio-data:
    driver: local


networks:
  trino-network:
    driver: bridge
